# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64fb1caa76e80be1a941f7bf21c9f1c089610e82c3ba697ad691294140973dcdb48f2ab62a61a57cbefe51b6eef143297063cbb5f024d4b5026cb37a60820b84

test:
  secret_key_base: cf04e5a3997195ffb1a6cf74b4b7b9157e5c4359e31d280a5c74deffa7c4d1d9abc2efcbb3ca71d5845c5451dcb3c9f163b53cbb7a0deb5dd0198c0c2a306c33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
